spring:
  application:
    name: AccountService

server:
  port: 8802

  eureka:
    client:
      fetch-registry: true
      register-with-Eureka: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka




